apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: PLACEHOLDER_AZURE_CONTAINER_REGISTRY.azurecr.io/as6-2_osso_chat_service:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MONGO_AZURE_CONNECTION_STRING
            - name: RabbitMQ
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RABBITMQ
            - name: Auth__Domain
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTH0_DOMAIN
            - name: Auth__Audience
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTH0_AUDIENCE
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: chat-service
  type: ClusterIP
